import os
# Output
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "logs")
OUTPUT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "logs"))
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Audio
AUDIO_SAMPLE_RATE = 16000
AUDIO_BLOCK_DURATION = 5

# Video
VIDEO_FPS_TARGET = 30
EAR_THRESHOLD = 0.25
EAR_CONSEC_FRAMES_CLOSED = 3
EAR_CONSEC_FRAMES_OPEN = 2

MAR_THRESHOLD = 0.7
MAR_CONSEC_FRAMES_OPEN = 5

ATTENTION_YAW_THRESHOLD = 25
PITCH_FOCUSED_MIN_ABS_THRESHOLD = 90
ATTENTION_CONSISTENCY_SECONDS = 3

HAND_RAISE_Y_THRESHOLD_FACTOR = 0.4
HAND_RAISE_COOLDOWN_SECONDS = 5
HAND_MOVEMENT_WINDOW_FRAMES = 90
HAND_MOVEMENT_STD_THRESHOLD = 0.04
HAND_MOVEMENT_COOLDOWN_SECONDS = 15

FATIGUE_YAWN_COUNT = 2
FATIGUE_YAWN_WINDOW_SECONDS = 60
FATIGUE_YAWN_COOLDOWN_SECONDS = 60

FATIGUE_BLINK_COUNT = 5
FATIGUE_BLINK_WINDOW_SECONDS = 10
FATIGUE_BLINK_COOLDOWN_SECONDS = 10
